<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AsyncImageLoader.Avalonia" Version="3.8.0" />
    <PackageVersion Include="FSharp.Core" Version="10.0.102" />
    <PackageVersion Include="LibChaCha20" Version="1.0.1" />
    <PackageVersion Include="NBitcoin.Secp256k1" Version="3.1.0" />
    <PackageVersion Include="Thoth.Json.Net" Version="12.0.0" />
    <!-- Avalonia UI -->
    <PackageVersion Include="Avalonia" Version="12.1.0" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageVersion Include="Avalonia.FuncUI" Version="2.0.0" />
    <PackageVersion Include="Avalonia.FuncUI.Elmish" Version="2.0.0" />
    <PackageVersion Include="Elmish" Version="5.0.2" />
    <PackageVersion Include="FsToolkit.ErrorHandling" Version="4.3.0" />
    <PackageVersion Include="LiteDB" Version="5.0.21" />
    <PackageVersion Include="Fumble" Version="2.0.1" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
    <PackageVersion Include="Suave" Version="3.4.6" />
    <!-- Unit testing -->
    <PackageVersion Include="FsUnit.xUnit" Version="5.2.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageVersion Include="coverlet.collector" Version="3.2.0" />
    <PackageVersion Include="xunit" Version="2.4.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.4.5" />
  </ItemGroup>
</Project>