<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <IsPackable>false</IsPackable>
        <RootNamespace>Nostra.Relay.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FSharp.Core" />
        <PackageReference Include="FsUnit.xUnit" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="Suave" />
        <PackageReference Include="coverlet.collector" >
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" >
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Nostra.Relay\Nostra.Relay.fsproj" />
      <ProjectReference Include="..\Nostra\Nostra.fsproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Include="ClientServer.fs" />
      <Compile Include="TestingFramework.fs" />
      <Compile Include="Nip01Tests.fs" />
      <Compile Include="Nip09Tests.fs" />
      <Compile Include="Nip11Tests.fs" />
      <Compile Include="Nip16Tests.fs" />
      <Compile Include="Nip33Tests.fs" />
      <Compile Include="Nip40Tests.fs" />
      <Compile Include="Nip45Tests.fs" />
      <Compile Include="Nip119Tests.fs" />
      <Compile Include="RelaySimpleTests.fs" />
    </ItemGroup>

</Project>
